services:
    facebook_messenger.messenger:
        class: Kerox\Messenger\Messenger
        arguments:
            bla: { access_token: %facebook_messenger.app_secret%, verify_token: %facebook_messenger.verify_token%, page_token: %facebook_messenger.page_token%, api_version: %facebook_messenger.api_version% }